export const actions = {
  ADD_POST: "ADD_POST",
  UPDATE_NEW_POST_TEXT: "UPDATE_NEW_POST_TEXT",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE_NEW_MESSAGE_BODY",
  SEND_MESSAGE: "SEND_MESSAGE",
  ALL_USERS: "ALL_USERS",
  ONE_USER: "ONE_USER",
  FOLLOW: "FOLLOW",
  UN_FOLLOW: "UN_FOLLOW",
  SET_USERS: "SET_USERS",
};
